### PR TITLE
Refactor code, inherit modules to the Flask service, and add a homepage

### PR DESCRIPTION
**Pull request by JessyTsu1**
To reduce the learning and usage costs for users, I decided to encapsulate commonly used modules in a Docker container.

However, after trying out  [someone else's packaged main function version](https://github.com/kaixindelele/ChatPaper/pull/124) I found that the packaging speed was very slow and not suitable for regular users, which contradicted my original intention.

Therefore, I decided to integrate four small script files, namely "arxiv", "paper", "response", and "reviewer", into a Flask service.

I also wrote a brief description on the homepage of the Flask service. This allows users to call different modules by starting a Flask service, and makes it easy to use directly on a server or with a frontend page in the future.

However, this is not cool enough as users still need to install corresponding configurations locally. Therefore, I plan to Dockerize the Flask service along this line of thinking on Friday and Saturday, allowing users to set up the Flask service locally or on a server with just a few simple commands.

Although this is an incomplete version, I would like to merge it into the main branch to show that I am working on something meaningful.

I will create another PR to improve the Docker version I mentioned above.

### CODE REVIEW

**Comment by JessyTsu1** [comment]
Related to feature request https://github.com/kaixindelele/ChatPaper/issues/121

**Comment by kaixindelele** [comment]
虽然我没太看懂，但是看起来很完善，哈哈，到时候有报错，我就艾特老哥帮忙维护一下~

**Comment by kaixindelele** [comment]
image-20230331042557655
这张图片没上传到GitHub上

**Comment by JessyTsu1** [comment]
> image-20230331042557655 这张图片没上传到GitHub上

我下一个feature一起完善

**Pull request merged**
